version: '3.4'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    privileged: true
    user: root
    volumes:
      - "./init/selenoid:/etc/selenoid"
      - "./init/selenoid/video:/opt/selenoid/video"
      - "./init/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "8", "-mem", "1g", "--service-startup-timeout", "70s", "-session-delete-timeout", "70s", "-session-attempt-timeout", "70s" ]
    ports:
      - "4444:4444"
    network_mode: bridge